; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-dev

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:scripts/check_offline_dependencies.py
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728
board_build.partitions = partitions_16mb.csv
board_build.filesystem = littlefs
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-s3-dev]
build_flags = 
	-DNOTUA_ALLOW_DEEP_SLEEP=0
lib_deps = h2zero/NimBLE-Arduino@^2.5.1

[env:esp32-s3-release]
build_flags = 
	-DNOTUA_ALLOW_DEEP_SLEEP=1
lib_deps = h2zero/NimBLE-Arduino@^2.5.1
